### PR TITLE
Fix/svg

### PR DESCRIPTION
**Pull request by tungd**
Hi, it turns out my previous fix for SVG rendering is not totally correct. It breaks when the SVG has two or more child nodes, the `isSvgMode` was reseted after the first child node. This update will only reset  the SVG context when exiting SVG element. There's some other tests broken but I'm able to run `jest -t 'render'`.

### CODE REVIEW

**Comment by tungd** [comment]
This probably will fix #448

**Comment by adamdbradley** [comment]
thanks!!

**Comment by sayjava** [comment]
Was this fix part of the 0.3 release? I am still not able to render more than 1 svg child node after upgrading.

**Comment by tungd** [comment]
@sayjava I believe it's not. You can check the [Change Log](https://github.com/ionic-team/stencil/blob/master/CHANGELOG.md) and commit log.

**Comment by aabm00** [comment]
Hi 

I have the same problem, only the first svg child is rendered, so is it still in process to solve the problem?

Thanks

**Pull request merged**
