### PR TITLE
feat(compiler): update glob and minimatch dependencies

### PR DESCRIPTION
**Pull request by christian-bromann**
## What is the current behavior?
We are currently using old versions of `glob` and `minimatch`.

## What is the new behavior?
Update them to latest.

## Documentation

n/a

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

The latest versions of these package require Node.js v16 and up which is what we require for Stencil v4 as well.

## Testing

I would assume as long as the build passes we are good to go.

## Other information

n/a

### CODE REVIEW

**Review by alicewriteswrongs — APPROVED** [review]
tried out the build locally in a sample project and in framework and everything looks good!

**Comment by rwaskiewicz** [comment]
Can we update renovate's config to stop ignoring these deps please?

**Review by tanner-reits — CHANGES_REQUESTED** [review]
Just blocking for Ryan's comment about Renovate

**Comment by christian-bromann** [comment]
Updated renovate file.

**Pull request merged**
