### PR TITLE
Added ChangeDetectionStrategy.OnPush to generated angular components

### PR DESCRIPTION
**Pull request by plchampigny**
Also reordered imports in @angular/core while adding ChangeDetectionStrategy import

### CODE REVIEW

**Comment by plchampigny** [comment]
Related to problem while compiling using ivy: https://github.com/ionic-team/ionic/issues/18403

**Comment by plchampigny** [comment]
Just for reference about the change from 0 to ChangeDetectionStrategy.OnPush:
https://angular.io/api/core/ChangeDetectionStrategy

**Comment by ElianCordoba** [comment]
Same issue here

**Comment by plchampigny** [comment]
@manucorporat If I backport the change to branck 0.18.x will you be able to update the branch and push the ionic team to fix this issue on next release?

**Comment by plchampigny** [comment]
https://github.com/ionic-team/stencil/pull/1578

**Pull request merged**
