### PR TITLE
IE11: Polyfill Infinite Loop - es6-collections vs core-js/map #1269

### PR DESCRIPTION
**Pull request by roNn23**
Hey! We want to use your awesome lib, but sadly Stencil isn't working with our stack (AngularJS) on IE11. We've got the same issue as mentioned in #1269 and fixed it by replacing the deprecated es6-collection lib with the more recent es6-shim lib. Because of this, we had to change some of the polyfills and refactored duplicated code. Please look into it and merge it, if possible. Thanks a lot!

### CODE REVIEW

**Comment by romulocintra** [comment]
Just add #1385  to make it optional !!!!

**Comment by fionawhim** [comment]
We were just bit by this. If core-js runs second, it tries to wrap / extend the es6-collection polyfill classes, modifying the `constructor` value, which causes the es6-collection constructors to go into an infinite loop.

Our hacky solution was to clear out the es6-collection versions of Map and Set before running core-js. 

Something more stable / contained would be ideal; it was a scary situation that upgrading Stencil broke the app on the page that we include Stencil in.

**Comment by stefanmeschke** [comment]
Any updates here? :)
Would like to see this merged? ;)

**Comment by dgibson666** [comment]
Any chance this can be fixed/implemented? We've been patiently awaiting a fix for months and are stuck on .15.2 as a result. I wonder how many other people are in the same boat.

**Comment by mattdsteele** [comment]
This should be resolved with Stencil One, as per @adamdbradley; it's using a different polyfill. You can try the prereleases and see the breaking changes here: https://github.com/ionic-team/stencil/blob/core-refactor/BREAKING_CHANGES.md

@manucorporat might be good to add the `fixed-with-stencil-one` label to this ticket :)

**Comment by manucorporat** [comment]
Fixed https://github.com/ionic-team/stencil/commit/5afaa7eee04e09ae626a06317ca82aec0bfd87c3

**Pull request closed without merging**
