### PR TITLE
fix(test): ensure legacy decorators are used when using transpile

### PR DESCRIPTION
**Pull request by louis-bompart**
## What is the current behavior?
Currently, file compiled through `stencil test` do uses the new ECMA decorators, contrary to the output of `stencil build` which always uses legacy TS decorators.
This, combined with what I think might be an issue with how TypeScript handles class modifiers updates, causes the behavior described in #4631.

GitHub Issue Number: #4631 

### Rejected fix:
Fixing/bypassing the TypeScript update behavior leaves us using the new decorators for `stencil test`, but the legacy ones for `stencil build`. The difference in behavior between the test & the source is not a good thing, obviously.

### Proposed fix:
Ensure we do set the `experimentalDecorators` in the compiler options used by `stencil test`

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Testing

 - `patch-package` the behavior in https://github.com/Aadhisivam/stencil-demo/, runs the tests ✅ 
 - Tested on github.com/coveo/ui-kit. ✅ (caveat, we're impacted by https://github.com/ionic-team/stencil/issues/3831 too)

_____

Fixes: #4631

### CODE REVIEW

**Comment by rwaskiewicz** [comment]
Hey @louis-bompart 👋 

Thanks! 

Can you do me a favor and provide step-by-step instructions for testing this change? I'm having some issues trying to verify that this works as described against https://github.com/Aadhisivam/stencil-demo/, as the changes here don't appear to be affecting the failure output of the tests. Of course, I could always be doing something wrong, which is why I ask for step-by-step instructions here 🙂 Thanks!

**Comment by louis-bompart** [comment]
Hey @rwaskiewicz my bad, I should've included more reproducible steps 🤦 
https://github.com/louis-bompart/stencil-demo I forked & pushed a repo to see the fix, clone, npm i, npm test, all tests should be green

**Comment by rwaskiewicz** [comment]
Ah, thanks @louis-bompart! I'm gonna let CI run on the rest of the PR and see if that catches anything I missed.

**Review by rwaskiewicz — APPROVED** [review]
Thanks!

**Pull request merged**
