### PR TITLE
fix(globalStyle): nested files are not applied in watch mode

### PR DESCRIPTION
**Pull request by johnjenkins**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Unit tests (`npm test`) were run locally and passed
- [ ] E2E Tests (`npm run test.karma.prod`) were run locally and passed
- [ ] Prettier (`npm run prettier`) was run locally and passed

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Nested files are not applied on save in watch mode. 
Within src/compiler/plugin/plugin.ts, the `globalStyle` is run through `runPluginTransforms` whilst components are run through `runPluginTransformsEsmImports` < dependencies via imports are managed differently in both instances.

## What is the new behavior?

Nested `@import` files / dependencies are now added to the watch task in the same way for components styles and globalStyles

Fixes: https://github.com/ionic-team/stencil/issues/2635
Fixes: https://github.com/ionic-team/stencil/issues/2741
Fixes: https://github.com/ionic-team/stencil/issues/1908
Fixes: https://github.com/ionic-team/stencil/pull/1909

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Testing
Linked this PR to a local test repro (https://github.com/johnjenkins/test-stencil-style-hmr) - added various `@import` statements to the `globalStyle` file. Make changes to nested files and see the browser reload styles via hmr.

### CODE REVIEW

**Comment by jared-christensen** [comment]
I'm curious why this never got merged. I'm using some imports in my globalStyle SCSS file and am looking for this functionality.

**Comment by jared-christensen** [comment]
I'm using this node script to watch for changes and it works OK. I just start it after I start my stencil server.

watcher.js
```javascript
const chokidar = require('chokidar');
const fs = require('fs');
const path = require('path');

// Define the directory and the file to touch upon changes
const watchDir = path.join(__dirname, 'src/css');
const fileToTouch = path.join(__dirname, 'src/index.scss'); // Adjust this path as needed

// Instantiate the file watcher
const watcher = chokidar.watch(`${watchDir}/**/*.scss`, {
  ignored: /(^|[\/\\])\../, // ignore dotfiles
  persistent: true,
});

// Define the event handlers
watcher
  .on('change', path => {
    console.log(`File ${path} has been changed`);
    touchIndex();
  })
  .on('add', path => {
    console.log(`File ${path} has been added`);
    touchIndex();
  });

// Function to "touch" the index.scss file
function touchIndex() {
  const time = new Date();
  fs.utimes(fileToTouch, time, time, err => {
    if (err) {
      console.log(err);
      return;
    }
    console.log(`Touched ${fileToTouch}`);
  });
}
```

package.json
```json
"scripts": {
  "watcher": "node ./watcher.js",
}
```

**Comment by jabbett** [comment]
@jared-christensen Thanks for this! I wrote a small bash script to run the watcher in parallel with `npm start`:

```
#!/bin/bash

node ./watcher.js & pid=$!
PID_LIST+=" $pid"

npm start & pid=$!
PID_LIST+=" $pid"

trap "kill $PID_LIST" SIGINT

printf "\nStencil development mode starting with workaround SCSS watcher\n\n"

wait $PID_LIST

printf "\n\nAll processes terminated\n\n"
```

Also - might be useful to note that the `fileToTouch` needs to be in a separate directory from the `watchDir` ;)

**Comment by rwaskiewicz** [comment]
Hey folks,

Please do me a favor and add 👍's to the issue summary to upvote it instead of "+1" style comments.  GitHub doesn't give us an easy way to track those types of comments, which makes them more likely to not be properly counted when we prioritize issues/PRs. 

Thanks!

**Comment by christian-bromann** [comment]
@johnjenkins thanks for providing the PR. I've adopted the patch in https://github.com/ionic-team/stencil/pull/5244 which was released today in Stencil v4.11.0.

**Pull request closed without merging**
