### PR TITLE
enhancement: Add better TS definition support to style attribute

### PR DESCRIPTION
**Pull request by kevinclarkadstech**
- Add csstype library
- Change style prop from an index signature object to use csstype

### CODE REVIEW

**Comment by adamdbradley** [comment]
This will have to be updated because the `csstype` package wouldn't be installed by the user since it'd be a devDependency. Additionally, we'd prefer it to not be another dependency, so we'll have to talk how to proceed on this.

**Comment by kevinclarkadstech** [comment]
> This will have to be updated because the `csstype` package wouldn't be installed by the user since it'd be a devDependency. Additionally, we'd prefer it to not be another dependency, so we'll have to talk how to proceed on this.

But when installing stencil as a dev dependency for doing a project, i.e. ionic pwa toolkit, won't that install dependencies stencil needs?

I understand about the dependency though..well the DOM attributes are fairly stable...maybe just copy over the content of the definitions from ```csstype```?

**Comment by kevinclarkadstech** [comment]
?

**Comment by simonhaenisch** [comment]
@kevinclarkadstech the goal is to keep the dependencies as few as possible, and at the moment `typescript` is the only dependency that is installed by Stencil. Any other dependencies are bundled into Stencil, so the user doesn't have to worry about these. And only the needed parts of each dependency are bundled which keeps Stencil lean and quick to install.

**Comment by manucorporat** [comment]
Style could also accept css variables:
```
style={{
 '--variable': something
}}
```

I don't think this types would be flexible enough

**Comment by manucorporat** [comment]
Thank you very much for this PR, but It's very unlikely to merge this PR, it would add a new dependency and it would not be compatible with css variables out of the box.

**Comment by kevinclarkadstech** [comment]
That makes sense.  However, I still consider this to be an open issue @manucorporat @adamdbradley .  Is this something you will work on in the future?  The HTML style attribute is very stable, you could just copy and paste from csstype lib into your d.ts file if you don't want another dependency.  The reason it's less of an issue for me is because I know css very well and know about the different camel casing vs kebab casing after using React + JSX, but I can imagine a developer newer to JSX and Stencil would find lack of TypeScript support pretty frustrating.

**Pull request closed without merging**
