### PR TITLE
fix(runtime): add missing intermediate parents scope ids to the elements

### PR DESCRIPTION
**Pull request by yigityuce**
## What is the current behavior?

GitHub Issue Number: #5774

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by christian-bromann** [comment]
@yigityuce thanks for the PR. I wonder if we can have a WDIO component test for this 🤔

**Comment by yigityuce** [comment]
> @yigityuce thanks for the PR. I wonder if we can have a WDIO component test for this 🤔

@christian-bromann  added test cases 🧪

**Comment by yigityuce** [comment]
@christian-bromann & @alicewriteswrongs test cases are updated to remove duplicated await statement

**Review by christian-bromann — APPROVED** [review]
👍

**Comment by yigityuce** [comment]
thanks @christian-bromann we are waiting someone else to approve too right?

**Review by tanner-reits — APPROVED** [review]
LGTM!

**Pull request merged**
