### PR TITLE
fix(runtime): nested multiple default slot relocation

### PR DESCRIPTION
**Pull request by yigityuce**
## What is the current behavior?

1. `getHostSlotNode` method was getting the first found slot node. However, the same slot name or even another custom component's default slot can be placed before the searching host element's slot node.
2. within the nested component structure, already relocated nodes were getting re-ordered by updating the anchor node which is used by insertBefore

GitHub Issue Number: #5335 

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by christian-bromann** [comment]
@yigityuce mind taking a look into the failing e2e test for this? You fix works on initial render but fails if the state of the application changes and e.g. a new element is rendered conditionally.

**Comment by christian-bromann** [comment]
@yigityuce it seems like the end-to-end tests are failing due to this patch. The order of element fails when a component is conditionally rendered, e.g.: the following Stencil component:

```tsx
@Component({
  tag: 'conditional-rerender-root',
})
export class ConditionalRerenderRoot {
  @State() showContent = false;
  @State() showFooter = false;

  componentDidLoad() {
    this.showFooter = true;
    setTimeout(() => (this.showContent = true), 20);
  }

  render() {
    return (
      <conditional-rerender>
        <header>Header</header>
        {this.showContent ? <section>Content</section> : null}
        {this.showFooter ? <footer>Footer</footer> : null}
      </conditional-rerender>
    );
  }
}
```
Results in the following:

Screenshot 2024-03-05 at 3 48 23 PM

Mind taking a look?

**Comment by yigityuce** [comment]
hey @christian-bromann & @rwaskiewicz 

I just pushed the fix for the regression issue that we were facing with the first implementation. Also, added the e2e tests. Please let me know if you want me to add anything else

**Comment by yigityuce** [comment]
did you have a chance to check this out? @christian-bromann @rwaskiewicz

**Comment by christian-bromann** [comment]
@yigityuce thanks for updating the PR and adding tests. Unfortunately since the PR was raised we started a migration process away from Karma to WebdriverIO. Can you do me a favor and migrate the tests you've written in Karma to WebdriverIO? It should be straightforward (copy&paste) and you can find a step by step description in our [migration trackker issue](https://github.com/ionic-team/stencil/issues/5458). Please let me know if you have any questions along the way and apology for throwing this at you 😝

**Comment by yigityuce** [comment]
hahah no worries @christian-bromann if this helps you in a way, I would do it right away. It will be ready at most 30 mins 🕺

**Comment by yigityuce** [comment]
@christian-bromann  done for this fix and also migrated the previous two PR's tests:

- slot-conditional-rendering #5365 
- slot-ref #5337

**Review by christian-bromann — APPROVED** [review]
Thanks a lot, I think this PR is good to 🚢 

I will let the @ionic-team/stencil team to have a another look at it

**Comment by yigityuce** [comment]
anything I can do? @christian-bromann @rwaskiewicz

**Comment by rwaskiewicz** [comment]
I'll make sure we get some time allocated to this next sprint. At the moment, we have our hands full with other initiatives

**Comment by rwaskiewicz** [comment]
@yigityuce Can you do me a favor and rebase this when you get a chance? We landed the migration of the `slot-conditional-rendering` suite in https://github.com/ionic-team/stencil/pull/5578 and the `slot-ref` suite in https://github.com/ionic-team/stencil/pull/5579, which I think we can safely drop from this PR.

**Comment by yigityuce** [comment]
> @yigityuce Can you do me a favor and rebase this when you get a chance? We landed the migration of the `slot-conditional-rendering` suite in #5578 and the `slot-ref` suite in #5579, which I think we can safely drop from this PR.

sure will be ready in 10 mins!

**Comment by yigityuce** [comment]
hey @rwaskiewicz it's been a month since this PR was created and did what you asked for. Could you pls prioritize this one since we are blocked? Please feel free to reach me for any additional requests or questions. I will get back to you ASAP.

**Review by tanner-reits — APPROVED** [review]

**Comment by tanner-reits** [comment]
@yigityuce Thanks for your patience over the last couple weeks as the team's been tied up with other initiatives! Code changes look good so I went ahead and rebased this so all of CI could run. Everything passed so gonna hit that magic green button and get this landed. It'll be included in our next Stencil release (slated for 4/8)!

Thanks for your contribution!

**Pull request merged**
