### PR TITLE
feat: Allow user defined commonjs or nodeResolve to override the default in Stencil

### PR DESCRIPTION
**Pull request by jordanranz**
When nodeResolve is executed after commonjs in the rollup plugin order, `Node Polyfills Required` error occurs even if `nodePolyfills()` is included as a plugin inside of `stencil.config.ts`.

Example error message:
```
[ ERROR ]  Node Polyfills Required
           For the import "buffer" to be bundled from ../amazon-cognito-identity-js/es/AuthenticationHelper.js, ensure
           the "rollup-plugin-node-polyfills" plugin is installed and added to the stencil config plugins. Please see
           the bundling docs for more information. Further information: https://stenciljs.com/docs/module-bundling
```

Related issues: https://github.com/ionic-team/stencil/issues/1719, https://github.com/ionic-team/stencil/issues/1471

[Related post on Rollup repo](https://github.com/rollup/rollup/issues/1148) stating '`node-resolve` has to come before `commonjs`.'

The following examples from plugin repos show nodeResolve before commonjs:
[node-resolve plugin example](https://github.com/rollup/rollup-plugin-node-resolve#using-with-rollup-plugin-commonjs)
[commonjs plugin example](https://github.com/rollup/rollup-plugin-commonjs#usage)

**UPDATE**
To alleviate this issue while also providing backwards compatibility, I have updated the code change to allow a user to pass in their own `commonjs` or `nodeResolve` Rollup plugins in a custom order.

### CODE REVIEW

**Comment by manucorporat** [comment]
That change would break other things: https://github.com/ionic-team/stencil/commit/69980f1892cacb50ddf21ffa6e630c5fa1dec547#diff-853dd3329fd29e1c3b019ec7a3c5b7cb

**Comment by jordanranz** [comment]
Interesting. Would it be possible to move the user plugins above the nodeResolve plugin in the execution order or do they have to be after commonjs?

**Comment by cptflammin** [comment]
Any update on this ?

**Comment by FelschR** [comment]
Having this issue when using `aws-amplify`.
Configured `nodePolyfills()` but still getting `Node Polyfills Required` errors.
Is there any workaround?

**Comment by cptflammin** [comment]
The Amplify team is working on it and seems there should be a fix in the upcoming weeks. In the meantime, in order to avoid to be blocked in development:
```
index.html: <script src=“https://unpkg.com/aws-amplify@1.1.36/dist/aws-amplify.min.js“></script> to be inserted before </head>
authentication.service.ts:
```
```
import awsmobile from “../aws-exports”;
class AuthenticationService {
 private _amplifyService: any;
 async init() {
   this._amplifyService = window[‘aws-amplify’];
   console.log(this._amplifyService);
   // configure Amplufy Auth with Amazon Cognito User Pools
   this._amplifyService.Auth.configure({
     ‘identityPoolId’: awsmobile.aws_cognito_identity_pool_id,
     ‘region’: awsmobile.aws_cognito_region,
     ‘userPoolId’: awsmobile.aws_user_pools_id,
     ‘userPoolWebClientId’: awsmobile.aws_user_pools_web_client_id,
   });
 }
 /** Sign Up a new user **/

 signUp(email: string, password: string) {
   this._amplifyService.Auth.signUp(
     {
       username: email,
       password: password,
       attributes: {          // optional
         email: email,
         // phone_number: ‘’,
       },
       // validationData: []  //optional
     }
   )
     .then((data) => {
       /*ISignUpResult:
       user: CognitoUser;
       AttributeName: “email”
       DeliveryMedium: “EMAIL”
       userConfirmed: boolean; // false
       userSub: string; // uuid.v4
       */
       console.log(‘result: ’, data);
       return data;
     })
     .catch((error) => {
       console.error(error);
       // console.log(error.message);
       return error;
     });
 };
etc.
}
```

**Comment by jordanranz** [comment]
Any updates on this?

**Comment by simonhaenisch** [comment]
The original reason for moving user plugins before `node-resolve` was to allow for (custom) virtual modules to be resolved first (see #1357).

However there must have been some issue with running user plugins before the `commonjs` plugin (I don't know why), so @manucorporat moved both user plugins and `node-resolve` behind `commonjs` (see 3adfaad2e6878a8f819145dff23bf582cf76b301). That broke the rule that Rich Harris stated:

> `node-resolve` has to come before `commonjs`.

So the problem is: the `commonjs` plugin should run before the user's plugins but the `node-resolve` plugin should run after (which implies that `commonjs` would need to come first). Not sure there's a solution for this.

**Comment by jordanranz** [comment]
I will submit a PR to conditionally load `commonjs` or `nodeResolve` from user defined Rollup plugins, which will allow for a custom order but also provide backwards compatibility to the concerns above.

**Comment by PatidarParth** [comment]
Hi, just wondering if there are any updates to this? I am trying to also integrate cognito with stencil but keep getting rollup plugin error. First I was getting the same error as the initial post but then added in node polyfill, global and builtin plugins. This then gave us this error 

`Rollup: Plugin Error
Unexpected token (33:30) in /Users/Documents/Sustainability App/sustainability-app-front-end/front-end/node_modules/@ionic/core/dist/collection/components/item-sliding/lazy_kfau14o4ceh3bv4ijlua-item-sliding.js (plugin: at position 10, transform)`

Any idea on how we can resolve this problem. Or if anyone has any stencil and aws cognito example code?

**Pull request closed without merging**
