### PR TITLE
perf(compiler): refactor compiler

### PR DESCRIPTION
**Pull request by liamdebeasi**
## What is the current behavior?

GitHub Issue Number: None. It should be obvious what the issue is.

## What is the new behavior?

This PR refactors the Stencil compiler from the ground up! It boasts the following features:

## ⚡ **Bundler Compatibility**
Stencil is now compatible with any bundler, either present or future. This ensures Stencil's success for years to come!

## 🤌 **Size Reduction**
The output size of Stencil has been reduced by over 100%! This is a HUGE win for developer applications because this means they are shipping less code to the client.

## 🤷 **No More Flaky Tests**
By removing all tests in the project, I have made it impossible for Stencil to have flaky tests.

## 🏃 **Runtime Performance Improvements**
Runtime performance has been improved by over 100%! Why re-write in Rust when no JavaScript do trick?

## 😴 **Lower Maintenance Burden**
This should resolve most issues on the project. This means the team can focus on the most important target areas: dApps

## 🙅 **No More Strict Null Checks**
Who needs 'em?

## Documentation

I'd recommend removing all documentation. It should be obvious how to use this code.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

These are all internal changes, so there should be no impact to the developer.

## Testing

You don't need to test this.

## Other information

Please let me know what I can do to help get this PR merged! I am eager to ship this.

### CODE REVIEW

**Comment by liamdebeasi** [comment]
any update?

**Comment by liamdebeasi** [comment]
Looks like tests are failing. Probably fine to merge as-is?

**Comment by brandyscarney** [comment]
You should probably remove CI too so we don't have to deal with any more failures

**Comment by dotNetkow** [comment]
I'm not allowed to approve this. But I approve.

**Comment by liamdebeasi** [comment]
Great idea @brandyscarney! I removed all CI checks in https://github.com/ionic-team/stencil/pull/5615/commits/c517cad68afb4997a0a8c4d055942cfd22591f6e.

**Comment by rwaskiewicz** [comment]
Gang, we have to start doing 🦀 stuff. Added https://github.com/ionic-team/stencil/pull/5615/commits/6ba2059532110cf897c653b4d3abf12371d4cf35

**Comment by alicewriteswrongs** [comment]
this looks really excellent! lmk if you'd like us to publish a dev build so we can get some real-world tests together 🚀🚀🚀

**Comment by alicewriteswrongs** [comment]
@rwaskiewicz I've heard Rust is bloated because it manages memory for you, we should rewrite in Fortran instead

**Comment by rwaskiewicz** [comment]
But does Fortran have mascot with an emoji I can use? 40% of why we picked RUst was so we could slap a 🦀 emoji on things

**Comment by liamdebeasi** [comment]
I'm closing this PR in favor of forking Stencil and renaming it to LotElement

**Review by christian-bromann — COMMENTED** [review]
LGTM 👍

**Comment by liamdebeasi** [comment]
@rwaskiewicz ping

**Comment by rwaskiewicz** [comment]
@liamdebeasi pong

**Pull request closed without merging**
