### PR TITLE
feat(compiler): add check for potential custom element name issue#947

### PR DESCRIPTION
**Pull request by ps011**
This PR will resolve [#947](https://github.com/ionic-team/stencil/issues/947) 
I have added a check for tag name of a custom component as defined [here](https://html.spec.whatwg.org/multipage/custom-elements.html#valid-custom-element-name)
I have taken reference from [here](https://github.com/mathiasbynens/mothereff.in/blob/master/custom-element-name/vendor/is-potential-custom-element-name.js)
I have seen that this issue is listed on-deck on the [project](https://github.com/ionic-team/stencil/projects/1) page. So, I picked it up. This is my first try to contribute code in stencil. Do let me know if there is any correction in this PR or code.

### CODE REVIEW

**Comment by adamdbradley** [comment]
Would you be able to add some unit tests for this? Thanks

**Comment by ps011** [comment]
@adamdbradley , Yes sure. Do I need to squash the commits as well?

**Comment by adamdbradley** [comment]
Nope no need to squash. I'll be able to squash merge this into master, no worries. Thanks for the help!

**Comment by adamdbradley** [comment]
Actually would you be able to move that code to here: https://github.com/ionic-team/stencil/blob/master/src/compiler/transpile/datacollection/component-decorator.ts#L21

**Comment by ps011** [comment]
I need to add another `if` condition right to test the tag name, right?

**Comment by adamdbradley** [comment]
Yeah, add all the checks there, and if a tag doesn't pass the test there should be a nice error that's log with an explanation of what to fix.

**Comment by ps011** [comment]
Okay, cool. I'll add that and push the code.

**Comment by ps011** [comment]
Another thing is, [this](https://html.spec.whatwg.org/multipage/custom-elements.html#valid-custom-element-name) mentions that a hyphen(-) is mandatory for a valid component name, and if I add that some test cases can fail. So, do we need to add that check? because it's a web component standard.
[This](https://mothereff.in/custom-element-name) can help in verifying component names

**Comment by adamdbradley** [comment]
Yup that's a good idea. Anything and everything we can do to validate the tag name the better.

**Comment by ps011** [comment]
Okay. I'll do this today. Thanks for the quick replies.

**Comment by ps011** [comment]
@adamdbradley , I have done the changes.

**Comment by adamdbradley** [comment]
Merged! thanks!

**Pull request merged**
