### PR TITLE
chore(build): remove rollup build infrastructure

### PR DESCRIPTION
**Pull request by alicewriteswrongs**
this comprises:

- the rollup bundle files
- making the esbuild code now the default
- renaming the modules in `scripts/bundles/plugins` which we want to keep around
- removing the `build-rollup` CI as well as the configuration in other workflows for which build to use

## What is the current behavior?

GitHub Issue Number: N/A

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Testing

It's a good idea for us to make sure that a dev release works properly, and probably a good idea to test that fairly extensively in framework and whatnot.

I published a dev build with the version `4.17.1-dev.1713982255.c28d937`, install it like so:

```sh
npm install @stencil/core@4.17.1-dev.1713982255.c28d937
```

### CODE REVIEW

**Review by rwaskiewicz — COMMENTED** [review]
FWIW, I think we should hold off on this for a few weeks while we resolve any lingering esbuild vs rollup build differences

**Comment by alicewriteswrongs** [comment]
agreed - I'm just opening it now, I'll put it as a draft though

**Review by christian-bromann — APPROVED** [review]
LGTM 🔪

**Review by tanner-reits — APPROVED** [review]
🪓 🪓 🪓

**Pull request merged**
