### PR TITLE
feat(cli): update flag defaults for V3

### PR DESCRIPTION
**Pull request by tanner-reits**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [X] Build (`npm run build`) was run locally and any changes were pushed
- [X] Unit tests (`npm test`) were run locally and passed
- [X] E2E Tests (`npm run test.karma.prod`) were run locally and passed
- [X] Prettier (`npm run prettier`) was run locally and passed

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [X] Other (please describe): Updates CLI flag defaults for `sourceMaps` on the Stencil config and `generateTypeDeclarations` on the `dist-custom-elements` output target

## What is the current behavior?

- Stencil config `sourceMaps` flag defaults to `false`.
- `dist-custom-elements` config `generateTypeDeclarations` flag defaults to `false`

GitHub Issue Number: N/A

## What is the new behavior?

**NOTE:** Only affecting Stencil V3
- Stencil config `sourceMaps` flag now defaults to `true`.
- `dist-custom-elements` config `generateTypeDeclarations` flag now defaults to `true`

## Does this introduce a breaking change?

- [X] Yes
- [ ] No

Will be covered in V3 migration guide

## Testing

Updated unit tests for custom-element output target, validating the stencil config, and validating the stencil config sourceMaps flag.

### CODE REVIEW

**Comment by tanner-reits** [comment]
I'll follow-up with a PR to update the breaking changes doc that links out to this PR

**Review by rwaskiewicz — COMMENTED** [review]
Tested by building this branch, `npm pack`ing the result, then installing the resulting tarball into the output of `npm init stencil@latest component v3-default-test`.

In the generated project, I 
- removed `dist` from the default output targets
- `npm run build`, observed that sourcemaps were generated, types were generated for `dist-custom-element`
- `rm -rf dist loader www` for a clean slate
- set`config.sourceMap: false` & `config.outputTargets.distCustomElements.generateTypeDeclarations: false`, observed neither sourcemaps nor types were generated
- `rm -rf dist loader www` for a clean slate
- set`config.sourceMap: true` & `config.outputTargets.distCustomElements.generateTypeDeclarations: true`, observed both sourcemaps & types were generated.

Taking a pass at `stencil-site` to see if anything needs to be changed there

**Comment by rwaskiewicz** [comment]
@tanner-reits can you put up a PR in `stencil-site` to update the docs against the [`Stencil-Site@v3.0.0-dev branch`](https://github.com/ionic-team/stencil-site/tree/v3.0.0-dev)?

Specifically, we need to update
- https://stenciljs.com/docs/custom-elements#generatetypedeclarations, which maps to https://github.com/ionic-team/stencil-site/blob/master/src/docs/output-targets/custom-elements.md?plain=1#L72
- https://stenciljs.com/docs/config#sourcemap, which maps to https://github.com/ionic-team/stencil-site/blob/master/src/docs/config/overview.md?plain=1#L181

**Review by rwaskiewicz — CHANGES_REQUESTED** [review]
Requesting a PR on the doc site to tie back to this PR before we merge it

**Comment by tanner-reits** [comment]
> @tanner-reits can you put up a PR in `stencil-site` to update the docs against the [`Stencil-Site@v3.0.0-dev branch`](https://github.com/ionic-team/stencil-site/tree/v3.0.0-dev)?
> 
> Specifically, we need to update
> 
> * https://stenciljs.com/docs/custom-elements#generatetypedeclarations, which maps to https://github.com/ionic-team/stencil-site/blob/master/src/docs/output-targets/custom-elements.md?plain=1#L72
> * https://stenciljs.com/docs/config#sourcemap, which maps to https://github.com/ionic-team/stencil-site/blob/master/src/docs/config/overview.md?plain=1#L181

@rwaskiewicz Docs updated [here](https://github.com/ionic-team/stencil-site/pull/899)

**Review by rwaskiewicz — APPROVED** [review]

**Pull request merged**
