### PR TITLE
fix(mock-doc): allow urls as css values

### PR DESCRIPTION
**Pull request by scaredcat**
CSS values such as `background-image: (https://mydomain.com/image.jpg)` currently loses values after the second colon. This ensures the entire value is taken into account when a url is specified.

### CODE REVIEW

**Comment by manucorporat** [comment]
Looks legit, it might be interesting to add a new failing test, but so far makes sense!

**Comment by scaredcat** [comment]
> Looks legit, it might be interesting to add a new failing test, but so far makes sense!

Added tests

**Review by rwaskiewicz — APPROVED** [review]

**Comment by rwaskiewicz** [comment]
Thanks!

**Comment by rwaskiewicz** [comment]
(sorry for the spam, labeling this so that I can get it ingested in our internal issue/release tracker)

**Comment by rwaskiewicz** [comment]
This fix has been included in the [v2.12.0 release](https://github.com/ionic-team/stencil/releases/tag/v2.12.0). I'm going to close this issue, however if the problem reappears, please feel free to open a new issue!

**Pull request merged**
