### PR TITLE
fix(compiler): propagate events in Angular proxies' event emitters

### LINKED ISSUE #1025: [Compiler/Angular] EventEmitters are not wired correctly
**Stencil version:**

```
 @stencil/core@0.11.4
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

Ionic 4 above Angular does not propagate events to the `EventEmitter`s declared in the Angular proxy components.

**Expected behavior:**

We expect the events to be correctly propagated.

**Steps to reproduce:**

You can spot the problem by, for instance, modifying the `ionic/angular/test/testapp` test application as follows:

1) In `ionic/angular/test/testapp/src/app/content/content-page.component.ts` add some logging for the `ionScroll` event (the interesting part is the `toggleLogEvents()` method):
```typescript
import { Component, ViewChild } from '@angular/core'
import { Content } from "@ionic/angular"

@Component({
  selector: 'app-card-page',
  styles: [
    `
      div.box {
        display: block;
        margin: 15px auto;
        max-width: 150px;
        height: 150px;
        background: blue;
      }

      div.box:last-of-type {
        background: yellow;
      }
    `
  ],
  template: `
  <ion-app>
  <ion-header #header>
    <ion-toolbar style="display: none" #toolbar>
      <ion-title>Hidden Toolbar</ion-title>
    </ion-toolbar>
    <ion-toolbar>
      <ion-title>Content - Basic</ion-title>
    </ion-toolbar>
  </ion-header>

    <ion-content padding style="text-align: center" #content>
      <p>
        <ion-button (click)="toggleFullscreen(content)">Toggle content.fullscreen</ion-button>
      </p>
      <p>
        <ion-button (click)="toggleLogEvents()">Toggle log scroll events</ion-button>
      </p>
      <p>
        <ion-button (click)="toggleDisplay(header)" color="secondary">Toggle header</ion-button>
        <ion-button (click)="toggleDisplay(footer)" color="secondary">Toggle footer</ion-button>
        <ion-button (click)="toggleDisplay(toolbar)" color="secondary">Toggle 2nd toolbar</ion-button>
      </p>
      <div class="box"></div>
      <div class="box"></div>
      <div class="box"></div>
      <div class="box"></div>
      <div class="box"></div>
      <div class="box"></div>
      <div class="box"></div>
      <div class="box"></div>
      <div class="box"></div>
    </ion-content>


  <ion-footer #footer>
    <ion-toolbar>
      <ion-title>Footer</ion-title>
    </ion-toolbar>
  </ion-footer>
</ion-app>
  `
})
export class ContentPageComponent {

  private loggedEvents = false;
  private subscription = null;

  console = console

  @ViewChild(Content) content: Content;

  constructor() {}

  toggleFullscreen(content) {
    content.fullscreen = !content.fullscreen;
    console.log('content.fullscren =', content.fullscreen);
  }

  toggleDisplay(el) {
    el.style.display = !el.style.display ? 'none' : null;
  }

  toggleLogEvents() {
    this.loggedEvents = !this.loggedEvents

    if (this.subscription) {
      this.subscription.unsubscribe()
      this.subscription = null
    }

    this.content.scrollEvents = this.loggedEvents;
    if (this.loggedEvents) {
      this.subscription = this.content.ionScroll.subscribe((e: CustomEvent) => {
        console.log('ionScroll', e.detail);
      });
    }
  }
}
```
2) Run the test app, go to the Content page, and click the `Toggle log scroll events` button.
3) Observe that no event is logged in the console.

**Related code:**

It seems to me that the `outputsAuxFunction()` function in `https://github.com/ionic-team/stencil/blob/master/src/compiler/distribution/dist-angular.ts` doesn't wire correctly the events. I believe that it should be:

```typescript
function outputsAuxFunction() {
  return `
export function proxyOutputs(instance: any, el: ElementRef, events: string[]) {
  events.forEach(eventName => {
    instance[eventName] = new EventEmitter();
    el.nativeElement.addEventListener(eventName, (ev: any) => instance[eventName].emit(ev));
  });
}`;
}
```
with the relevant code later to insert the `ElementRef` as a second argument in the generated calls to `proxyOutputs()`.

**Other information:**

### PR DESCRIPTION
**Pull request by ptitjes**
Fixes #1025.

### CODE REVIEW

**Comment by manucorporat** [comment]
Thanks a lot for the PR! but I have the feeling that this will cause events to be dispatched twice when used in a template

**Comment by ptitjes** [comment]
@manucorporat You're welcome! Currently, events are not dispatched at all!! :/

**Comment by manucorporat** [comment]
yes they are if used in a template:
```
<ion-checkbox (ionChange)="event()">
```

**Comment by ptitjes** [comment]
@manucorporat I believe that the event registrations in templates are not using the event emitters declared on the proxies. To see that, do the following :

1) build fully ionic/core and ionic/angular
2) in `ionic/angular/src/directives/proxies.ts` modify the `Content` proxy by commenting the event emitter related information (also in the `@Directive`) like so:
```typescript
export declare interface Content extends StencilComponents.IonContent {}
@Directive({ selector: 'ion-content', inputs: ['color', 'fullscreen', 'forceOverscroll', 'scrollX', 'scrollY', 'scrollEvents']/*, outputs: ['ionScrollStart', 'ionScroll', 'ionScrollEnd']*/ })
export class Content {
  // ionScrollStart: EventEmitter<any>;
  // ionScroll: EventEmitter<any>;
  // ionScrollEnd: EventEmitter<any>;
  constructor(r: ElementRef) {
    proxyMethods(this, r, ['getScrollElement', 'scrollToTop', 'scrollToBottom', 'scrollByPoint', 'scrollToPoint']);
    proxyInputs(this, r, ['color', 'fullscreen', 'forceOverscroll', 'scrollX', 'scrollY', 'scrollEvents']);
    // proxyOutputs(this, ['ionScrollStart', 'ionScroll', 'ionScrollEnd']);
  }
}
```
3) in the `angular` directory, run `./node_modules/.bin/ngc` and `node ./scripts/clean-generated.js` again
4) go in the `angular/test/testapp/` directory and modify `src/app/content/content-page.component.ts` to add a `(ionScroll)` registration to the `ion-content` element:
```html
<ion-content padding style="text-align: center" #content
                 [scrollEvents]="true" (ionScroll)="logEvent('html', $event)">
```
with a corresponding method:
```
  private logEvent(origin: string, e: CustomEvent<ScrollDetail>) {
    console.log(`${origin} >> ${e.detail}`);
  }
```
5) run the testapp `npm run serve` (this also copies the result of the build of `ionic/angular`
6) in your browser, go to the content page of the testapp and **observe that the event are logged despite nothing is declared about it in the proxy !**

**Comment by manucorporat** [comment]
@ptitjes 
>@manucorporat I believe that the event registrations in templates are not using the event emitters declared on the proxies. To see that, do the following :


They use both, DOM events and event emitters, that's the problem. Just try it

**Comment by ptitjes** [comment]
This finally has been fixed by @manucorporat in https://github.com/ionic-team/stencil/commit/dabcf5ee74cb14c2a7a9f4801ee64b3f20fd48e5, so closing my PR.

@manucorporat Do not hesitate to ask me to enhance my PRs when they are not exactly what you expect...

**Pull request closed without merging**
