### PR TITLE
key and ref for all JSX elements

### PR DESCRIPTION
**Pull request by kraftwer1**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Unit tests (`npm test`) were run locally and passed
- [ ] E2E Tests (`npm run test.karma.prod`) were run locally and passed
- [ ] Prettier (`npm run prettier`) was run locally and passed

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

GitHub Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by kraftwer1** [comment]
@rwaskiewicz not sure if GitHub notifications work on closed PRs.
This PR is the one you've asked me to re-open here: https://github.com/ionic-team/stencil/pull/2925

Some checks seem to be failing, but since this PR only contains a tiny change of type information, I hope it's okay that I ignore all the failing browser tests as they're most probably completely unrelated.

**Comment by rwaskiewicz** [comment]
Thanks! It looks like this is failing the build step, specifically when we try to compile Stencil - it looks like TypeScript is having some trouble with those type definition changes:
Screen Shot 2021-12-15 at 8 07 27 AM

This is also why the tests are failing (because compilation is failing). Would you mind taking a look? This should be reproducible by running the following against this branch:
```
npm ci && npm run clean && npm run build
```
which installs dependencies like CI would, cleans out directories under the Stencil repo generated at build time, then kicks off the build.

**Comment by kraftwer1** [comment]
@rwaskiewicz thanks a lot, it works now!

**Review by rwaskiewicz — APPROVED** [review]
Thanks!

**Pull request merged**
