### PR TITLE
fix(compiler): support rollup's external input option

### PR DESCRIPTION
**Pull request by awk**
Pluck the external option from the stencil config and pass it through to rollup.

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [X] Build (`npm run build`) was run locally and any changes were pushed
- [X] Unit tests (`npm test`) were run locally and passed
- [X] E2E Tests (`npm run test.karma.prod`) were run locally and passed
- [ ] Prettier (`npm run prettier`) was run locally and passed

## Pull request type

 

 

Please check the type of change your PR introduces:
- [X] Bugfix
- [ ] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

GitHub Issue Number: https://github.com/ionic-team/stencil/issues/3226

## What is the new behavior?

The `external` option is now supported and works when added to the rollupConfig.inputOptions

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Testing

In my project (private - sorry) which has a complex set of module dependencies I can see that the desired module is no longer included in the stencil output.

### CODE REVIEW

**Comment by rwaskiewicz** [comment]
Thanks for this issue report! I see the accompanying PR and have labeled this issue for the team to take a look at both a little more closely.

**Comment by awk** [comment]
@rwaskiewicz Do you have an update on the process for this PR ? Any outstanding questions or issues?

**Comment by rwaskiewicz** [comment]
@awk I think the next steps for this PR is for the team to sit down and review the PR. Specifically, we'll be looking at the changes and convincing ourselves that it doesn't conflict with any internal rollup configuration Stencil currently does.  While I can't promise an exact timeline, we'll take a look as soon as we get a chance!

**Comment by rwaskiewicz** [comment]
In the mean time, I've enabled the rest of CI to run for this PR to make sure the rest of our checks pass

**Comment by TiagoVenceslau** [comment]
@rwaskiewicz Are there any updates on @awk 's PR? This would also be a very important feature for a project we're developing

**Comment by mikaelkaron** [comment]
This would be nice to include. The current workaround I'm using is based on [this](https://github.com/ionic-team/stencil/issues/2840#issuecomment-902656851) but with a slight modification:

```
  rollupPlugins: {
    before: [
      {
        name: 'overwrite-rollup-options',
        options: (options: RollupInputOptions) => ({
          ...options,
          external: ['@package/identifier']
        })
      }
    ]
  },

```

**Review by christian-bromann — APPROVED** [review]

**Comment by christian-bromann** [comment]
Add docs for this option in https://github.com/ionic-team/stencil-site/pull/1453

**Pull request merged**
