### PR TITLE
fix(runtime): transformTagName now impact CSS scope id

### PR DESCRIPTION
**Pull request by softwaymedical**
Fix: https://github.com/ionic-team/stencil/issues/2678 

**Question:** We would like to add some tests on this feature but didn't find any test on the transformTagName at runtime. Can you give us advice to add some ?

### CODE REVIEW

**Comment by softwaymedical** [comment]
Please note that the last commit introduce a breaking change, the transformTagName function should now verify that the transformed tag name is one of the library : 

```
var version = '1.0.6';
...
{
  transformTagName: function(originalTagName){
    // Do the transformation only if it is a component of our library 
    if(originalTagName.startsWith('swm-'))
      return version + '-' + originalTagName;
    return originalTagName;
  }
}
```

**Comment by softwaymedical** [comment]
We found another issue concerning the usage of the same nomodule library in different versions. 

```html
<body>
  <!-- ... -->
  <!-- data-opts.transformTagName = (i) => `1.0.6-${i}` -->
  <script src="<some-path>/lib/components/1.0.6/dist/swm-components/swm-components.js"></script>
  <!-- data-opts.transformTagName = (i) => `1.0.8-${i}` -->
  <script src="<some-path>/lib/components/1.0.8/dist/swm-components/swm-components.js"></script>
</body>
```

With the `getScriptElm` function as it is, will always return the `1.0.6` script (that will impact the retrieved options), even for the components of the `1.0.8`. 

We found a fix for that, but it is a very ugly one, and we hope you have some better way to do it: 

```javascript
export const getScriptElm = (): HTMLScriptElement => {
  // @ts-ignore
  if( BUILD.scriptDataOpts || BUILD.safari10 || BUILD.dynamicImportShim ){
    // Awfull way to retrieve currentScript source, sorry for that
    // if you have better, feel free to replace it ! :) 
    const currentScriptSource = (
      new Error().stack
      .split("\n")[0] 
      .split('@')[1]
      .split("/")
      .slice(0, -1)
      .join('/')
      .split(NAMESPACE)[0]
      + NAMESPACE
    );
    return Array.from(doc.querySelectorAll('script')).find(
      s => new RegExp(currentScriptSource).test(s.src) || s.getAttribute('data-stencil-namespace') === NAMESPACE,
    );
  }
  return null;
};
```

**Comment by softwaymedical** [comment]
@adamdbradley

Hi, 

We need this MR to add a Stencil component library to our legacy app.  
Did you have time to look into it ? Do you think this MR will interest you ?

Thanks

**Comment by softwaymedical** [comment]
@adamdbradley @manucorporat

Up ^_^

We did not have any feedback regarding this PR within a month.  
Can you tell us what do you think about it ? :) 

Thanks

**Comment by softwaymedical** [comment]
Hi, 

We just reworked the PR, it is now lighter than the first version of it. 
Please note that as mentioned before, this PR introduce a breaking change, the transformTagName function should now verify that the transformed tag name is one of the library: 

```
var version = '1.0.6';
...
{
  transformTagName: function(originalTagName){
    // Do the transformation only if it is a component of our library 
    if(originalTagName.startsWith('swm-'))
      return version + '-' + originalTagName;
    return originalTagName;
  }
}
```

**Comment by christian-bromann** [comment]
@softwaymedical sorry for getting back to you not earlier than 4 years later 🙈 

The Stencil team and project has been changing since this PR has been raised. At this point the new team members including myself don't know how to pick this work effort up. My suggestion is to re-raise the issue (if you still encounter it) and we can see if we can adopt provided code changes to the new code base.

I will close this PR but happy work with you on getting this shipped into the current version of Stencil.

**Pull request closed without merging**
