### PR TITLE
feat(config): add sassConfig option

### LINKED ISSUE #248: SCSS imports doesn't work for third party library
**Resources:**
Before submitting an issue, please consult our [docs](https://stenciljs.com/).

**Stencil version:** (run `npm list @stencil/core` from a terminal/cmd prompt and paste output below):

```
@stencil/starter@0.0.1 /root/bluma-elements
└── @stencil/core@0.0.6-13
```

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**

look at example repo here https://github.com/elmariofredo/bulma-elements/pull/1 where I'm trying to stencilize material design button. In example I'm importing scss from material design package which is trying to import another scss file from other md package. This will end up with following error 

```
[ ERROR ]  File to import not found or unreadable: @material/theme/_mixins. Parent style sheet:
           /root/bluma-elements/node_modules/@material/button/mdc-button.scss
```

this issue is well documented under material-components-web project 
https://github.com/material-components/material-components-web/issues/351 with resolution to add `node_modules` to `includePaths` in scss compiler settings.

**Expected behavior:**

Can we allow set scss config from stencil config?

**Steps to reproduce:**

checkout https://github.com/elmariofredo/bulma-elements/pull/1  branch and run `npm install && npm start`

**Related code:**

https://github.com/ionic-team/stencil/blob/9f3f347bb6ce4bdd314d86af6e237e29a58c2895/src/compiler/transpile/transpile.ts#L254-L256

**Other information:**

- https://github.com/material-components/material-components-web/issues/351

### PR DESCRIPTION
**Pull request by elmariofredo**
to allow sass compile fine tunning

Closes #248

### CODE REVIEW

**Comment by elmariofredo** [comment]
I'm not sure what is your approach as you seems to have facade as you are doing with `outputStyle` here https://github.com/elmariofredo/stencil/blob/master/src/compiler/bundle/component-styles.ts#L175 but I'm not sure if this approach is feasible in long run.

**Comment by adamdbradley** [comment]
looks great, thanks!

**Comment by adamdbradley** [comment]
Regarding the output style, it really doesn't matter because later on in the build we use CleanCSS on the bundled css file it generates. Only reason we put in the `compressed` option when minifying css is just to help out clean-css with less work from the start, but really probably doesn't matter much.

**Comment by elmariofredo** [comment]
Yeah I meant more what approach should we take regarding stenciljs config API, if it's better to make facade with custom config keys to prevent issues when there will be need to change sass backend or as I have proposed simply use pass thru options.

Anyway glad you like it

Cheers 🍻

**Comment by dertuerke** [comment]
How i can use it?

**Comment by elmariofredo** [comment]
@dertuerke you can just add property `sassConfig` to your stencil.config.js and add whatever options you desire. 

@adamdbradley we should properly document this feature, so I have created https://github.com/ionic-team/stencil-site/pull/110 but not sure if that is correct location. Let me know.

**Comment by dertuerke** [comment]
@elmariofredo i try it but it dosent work

```
sassConfig: '/node_modules/material-design-lite/src/ material-design-lite.scss'
```

**Comment by elmariofredo** [comment]
@dertuerke it should be 

```
sassConfig: {
  includePaths: ['./node_modules']
}
```

check https://github.com/sass/node-sass#includepaths for more details

**Pull request merged**
