### PR TITLE
feat(compiler): generate component custom event types with HTML target

### PR DESCRIPTION
**Pull request by sean-perkins**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Unit tests (`npm test`) were run locally and passed
- [x] E2E Tests (`npm run test.karma.prod`) were run locally and passed
- [x] Prettier (`npm run prettier`) was run locally and passed

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

The generated types for a web components custom event, does not include type definitions for the `target` value.

GitHub Issue Number: #3291

## What is the new behavior?

- Stencil compiler will generate new exported interfaces in `components.d.ts` for all web component that have custom events.
- The generated interfaces includes the typing to the generated HTML element type for the event target and accepts a generic for the custom event detail.
- Stencil compiler will generate the web component custom event type with the new type, allowing usage with the custom event and the generated HTML element type for the `target`. 

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Testing

The steps outlined below can apply to any Stencil project, but will outline against Ionic Framework:
1. Build and pack a local version of this branch
2. Install the .tgz into Ionic Framework `/core` project.
3. Run `npm run build` to build Stencil
4. See that in `components.d.ts` that there is a new namespace called `ComponentEvents`.
5. Build the react package, by running `npm run build` from `packages/react`
6. Sync the build changes with the react test app, by running `npm run sync` from `packages/react/test-app`.
7. Run the test-app `npm run start`
8. Modify any of these `.tsx` files (i.e. App.tsx) to use a web component with a JSX event listener that accesses a custom public method on the web component:
```tsx
<IonInfiniteScroll onIonInfinite={ev => ev.target.complete()}></IonInfiniteScroll>
```
9. Validate that there is no typing errors/exceptions. Intellisense/tsc is able to determine the type of the `complete()` function from `infinite-scroll.tsx`. 

## Other information

Closing #3286 in favor of this PR.

### CODE REVIEW

**Comment by sean-perkins** [comment]
I can open a PR to the Stencil docs site to account for these changes, if we agree with the approach and naming of the generated types.

**Comment by sean-perkins** [comment]
I could see us renaming the generated types to be: `ComponentEvents.IonAccordion` instead of `ComponentEvents.IonAccordionEventDetail` (as an example). But will wait until this gets a first look.

**Comment by rwaskiewicz** [comment]
@sean-perkins We landed #2936, which was blocking us from moving forward on this PR. LMK if you wanna sync up some time next week to figure out next steps for this one

**Comment by sean-perkins** [comment]
@rwaskiewicz Sounds good! I'll rebase and incorporate some of the changes we discussed offline (probably ~ mid next week). I'll reach out if I have questions with the latest 👍

**Comment by sean-perkins** [comment]
This PR has been updated. Unsure if you can re-run failed jobs or if I need to push an empty commit to re-trigger CI. I know we can re-run failed actions in framework, assume it is a contributor permission.

**Comment by rwaskiewicz** [comment]
yeah...must be a contributor permission thing. kicked it back off

**Review by rwaskiewicz — APPROVED** [review]

**Comment by moshner** [comment]
This is great! Thanks for adding it. Are there docs on how to use it?

**Comment by moshner** [comment]
Docs would be very helpful. Especially, for anyone who is consuming our web components and need to hook into events.

**Comment by jcfranco** [comment]
This is a great enhancement! Is there a particular reason why `currentTarget` isn't typed? Apologies if I'm missing something.

**Pull request merged**
