### PR TITLE
fix(runtime): scoped slot append/prepend correct order after interaction

### PR DESCRIPTION
**Pull request by yigityuce**
## What is the current behavior?

GitHub Issue Number: #5969

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by yigityuce** [comment]
to summarize, I added `s-sh` flag to the existing `prepend` patch and copied that block (s-ol and s-sh updating block) to the `appendChild` patch as well. 

the others (`InsertAdjacentHTML`, `InsertAdjacentText`, `InsertAdjacentElement`, `append`, etc) are using the `prepend` or `appendChild` internally, so they don't need to be updated

**Comment by christian-bromann** [comment]
@yigityuce do you think we can add a unit test for this change?

**Review by tanner-reits — CHANGES_REQUESTED** [review]
@yigityuce Changes look good! Only request would be to add a test like @christian-bromann suggested. You could probably add a Webdriver test to our existing test suite for these methods [here](https://github.com/ionic-team/stencil/blob/main/test/wdio/scoped-slot-append-and-prepend/cmp.test.tsx). Let me know if you have any questions!

**Comment by yigityuce** [comment]
hey @christian-bromann & @tanner-reits tests are added as a separate test file since to reproduce the issue, I need to remove the default slot wrapper and I didn't want to break the existing test case.

**Review by tanner-reits — APPROVED** [review]
@yigityuce Thanks! Everything looks good. I'll get this merged and try to get a release out this week!

**Comment by christian-bromann** [comment]
Released in Stencil `v4.22.0`

**Pull request merged**
