### PR TITLE
test(windows): fix build-modules.spec.ts

### PR DESCRIPTION
**Pull request by tja4472**
#670 build-modules.spec.ts fails on Windows

### CODE REVIEW

**Comment by adamdbradley** [comment]
What is the `TjaTestingCompiler` used for vs. just the TestingCompiler?

**Comment by tja4472** [comment]
The TjaTestingCompiler will set the config.rootDir to 'C:\' for Windows machines so that internally the tests will be using 'C:\src\' rather than '/src/.

In addition it has methods that will convert the '/src/' paths used in .spec files to 'C:\src\' for Windows machines.

At the moment any code under test which does a path.resolve() on a Windows machine will return 'C:\..' which more than likely will cause the test to fail, as internally the test is expecting '/src...';

**Comment by adamdbradley** [comment]
Is there any way this logic can be put into the TestingCompiler? I'd like to not make a specific class for just windows machines to work.

**Comment by tja4472** [comment]
In theory the code in TjaTestingCompiler can replace the code in TestingCompiler .

I had it as a separate class as I have no way of testing on non windows machines.

**Comment by tja4472** [comment]
Tested with ubuntu.

**Comment by adamdbradley** [comment]
Going to close this PR since there are conflicting issues. We'll keep looking and various approaches to fix this. Thanks

**Pull request closed without merging**
