### PR TITLE
chore(test): migrate `invisible-prehydration-false` to wdio

### PR DESCRIPTION
**Pull request by tanner-reits**
## What is the current behavior?

GitHub Issue Number: N/A

## What is the new behavior?

Migrates `test/karma/test-app/invisible-prehydration-false` to wdio. This involves adding some additional project files for a separate Stencil project build (Stencil config, tsconfig, `components.d.ts`). The test will inject an iframe into the browser DOM so the test can run "in isolation" (same pattern as #5591)

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
👍

**Comment by christian-bromann** [comment]
I think the BrowserStack pipeline will continue to fail since we don't run any tests in Karma anymore which usually causes a testrunner to fail.

**Comment by tanner-reits** [comment]
@christian-bromann Ryan Disabled the browserstack CI requirement so even if it fails this should still land

**Comment by tanner-reits** [comment]
I stand corrected 😂

**Comment by rwaskiewicz** [comment]
Us to this PR:
9Hb10vJh3t9GcmQ_

**Comment by christian-bromann** [comment]
🙌

**Pull request merged**
