### PR TITLE
Added ChangeDetectionStrategy.OnPush to generated angular components

### PR DESCRIPTION
**Pull request by plchampigny**
This is a backport of the other pr already merged in master
https://github.com/ionic-team/stencil/pull/1575

### CODE REVIEW

**Comment by plchampigny** [comment]
Are those tests failing because I backported in an old branch that doesn't support the new test scheme?

**Comment by plchampigny** [comment]
https://github.com/ionic-team/ionic/issues/18403

**Comment by plchampigny** [comment]
@adamdbradley are you planning on releasing stencil 1.0 on ionic soon? If so this PR is useless, otherwise I do think this could help the angular community if you made a 0.18.2 release on stencil and upgrade dependency on @ionic/core to 0.18.2

**Comment by simonhaenisch** [comment]
@plchampigny do you still need this backport? Otherwise I think we can close this now, as 1.0 has been released.

**Comment by plchampigny** [comment]
@simonhaenisch Well depending on your status on the ionic-team/ionic changes and expectation to release the next version with stencil v1.

I think that if you are months away from releasing with the stencil v1 in ionic, my PR should be incorporated and then released earlier in a minor version.
If stencil v1 is incorporated in next ionic version, this can be closed as it's irrelevant.

**Comment by simonhaenisch** [comment]
Ah right, this is about Ionic running on Stencil 1... sorry I didn't get that at first.

The master branch of Ionic is already on Stencil 1.0.x (see https://github.com/ionic-team/ionic/commit/b40f7d36d5802251a0b44a7dd2599f19dbe977d5) and thus it will be fixed with the next release which is going to be 4.6.0 afaik.

**Pull request closed without merging**
