### PR TITLE
fix(runtime): replace `innerHTML` with `textContent` for CSS injection

### PR DESCRIPTION
**Pull request by TheodoreGC**
This commit addresses security and performance concerns associated with using `innerHTML` for injecting CSS into `<style>` elements in `bootstrap-lazy.ts`.

By switching to `textContent`, the risk of executing malicious scripts is mitigated and performance is improved due to the avoidance of HTML parsing. This change enhances the security and efficiency of Stencil's component initialisation process, particularly in environments with strict security policies like browser extensions, without impacting functionality in standard web applications.

fixes: #5206

### CODE REVIEW

**Comment by rwaskiewicz** [comment]
👋 

I'm marking this as 'Awaiting Reply' for now, while we work on getting a reproduction case + a few additional questions answered in the issue associated with this PR.

**Comment by TheodoreGC** [comment]
Hey 👋,

Thanks for letting me know! I've updated the issue related to this PR with the bug reproduction project and all the requested information.

Let me know if there's anything else you need or if further details are required.

Thanks!

**Review by alicewriteswrongs — APPROVED** [review]
Just tested this out in the supplied repro case, and it looks good to me! I'm going to get this rebased and merge it in. Thanks for this contribution!

**Comment by christian-bromann** [comment]
This fix has been published in [v4.12.3](https://github.com/ionic-team/stencil/releases/tag/v4.12.3).

**Pull request merged**
