### PR TITLE
chore(docs): change the location of the Contributing Guidelines

### PR DESCRIPTION
**Pull request by JessicaSachs**
This commit moves the `CONTRIBUTING.md` file up to the project root which is more standard.

The old location (`.github/CONTRIBUTING.md`) still exists, but contains a message and link re-routing the user to the new location.

This is so that other repositories don't have to change their hard-link references to the old location of the Contributing Guidelines.

Other repositories will be updated over time.

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Unit tests (`npm test`) were run locally and passed
- [ ] E2E Tests (`npm run test.karma.prod`) were run locally and passed
- [x] Prettier (`npm run prettier`) was run locally and passed

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

GitHub Issue Number: N/A

## What is the new behavior?

- The `CONTRIBUTING.md` file has moved to the root of the project (this is more in line with modern convention).
- The old `.github/CONTRIBUTING.md` file has a link to the new place.
- All references within this repository point to the new hard link location.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Testing

Can't test the new link until the file is moved! 😅

### CODE REVIEW

**Review by rwaskiewicz — APPROVED** [review]
This looks good to me, thanks!

By being the first approver, that enables merging to occur once CI is green. For the time being, I'd like to have the rest of the team review each other's PRs. @alicewriteswrongs and @tanner-reits should have been requested to review this by our auto-assign bot. Once they take a look, this should be good to merge 🚢

**Review by tanner-reits — APPROVED** [review]
LGTM!

**Review by alicewriteswrongs — APPROVED** [review]
looks great! 👍 :shipit:

**Comment by rwaskiewicz** [comment]
Sweet - @JessicaSachs would you mind rebasing this to sync the branch with `main`? That should satisfy:
- The repo's setting to keep the branch up to date before merge
- The team's desire to keep a linear git commit history

Thanks!

**Pull request merged**
